# Generated by Django 5.0.6 on 2024-07-14 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_watchlist_avg_rating_watchlist_num_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='num_reviews',
            new_name='num_ratings',
        ),
    ]
